### ISSUE TITLE
Unpublishing article throws error - progress bar never completes

### ISSUE THREAD

**Issue by pfeytser** [nymag/clay-kiln#835]

**Comment by nelsonpecora** [comment]
looks like this is fixed

**Comment by pfeytser** [comment]
@nelsonpecora This is still happening for me on the Vue branch.

I publish an article. 
Go to view mode. 
Go back to edit mode.
Unpublish.

**Comment by nelsonpecora** [comment]
fixed in commit 1ffa2bc
